polyfills.ts: Add back es7/reflect
Because this is apparently needed on Firefox, to avoid this error
(seen in the Firefox console)

TypeError: Reflect.getMetadata is not a function